project_id = "swusayoygknritombbwg"

[functions.dicomweb-server]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.live-transcription]
verify_jwt = false

[functions.generate-diagnostic-report]
verify_jwt = true