project_id = "swusayoygknritombbwg"

[functions.dicomweb-server]
verify_jwt = false

[functions.dicomweb-proxy]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.live-transcription]
verify_jwt = false

[functions.generate-diagnostic-report]
verify_jwt = true

[functions.process-dicom-upload]
verify_jwt = false

[functions.direct-dicom-upload]
verify_jwt = false

[functions.get-pacs-study]
verify_jwt = true