project_id = "swusayoygknritombbwg"

[functions.dicomweb-server]
verify_jwt = false

[functions.dicomweb-proxy]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.live-transcription]
verify_jwt = false

[functions.generate-diagnostic-report]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = true

[functions.extract-dicom-zip]
verify_jwt = true