project_id = "swusayoygknritombbwg"

[functions.retry-failed-syncs]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.live-transcription]
verify_jwt = false

[functions.generate-diagnostic-report]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = true

[functions.extract-dicom-zip]
verify_jwt = true

[functions.backup-to-gcs]
verify_jwt = true

[functions.get-dropbox-upload-url]
verify_jwt = true

[functions.sync-case-to-dropbox]
verify_jwt = true

[functions.upload-report-to-dropbox]
verify_jwt = true

[functions.get-dropbox-file]
verify_jwt = true

[functions.mark-case-completed]
verify_jwt = true

[functions.check-dropbox-report]
verify_jwt = true

[functions.download-from-dropbox]
verify_jwt = true

[functions.pregenerate-case-zip]
verify_jwt = true

[functions.batch-pregenerate-zips]
verify_jwt = true

[functions.prepare-case-upload]
verify_jwt = true

[functions.sync-case-folders]
verify_jwt = true

[functions.complete-case-report]
verify_jwt = true

[functions.get-report-download-link]
verify_jwt = true

[functions.cleanup-failed-upload]
verify_jwt = true

[functions.monitor-system-health]
verify_jwt = true