-- Create PDF template settings table
CREATE TABLE public.pdf_templates (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL DEFAULT 'Default Template',
  logo_url TEXT,
  company_name TEXT DEFAULT 'DentaRad',
  company_address TEXT,
  primary_color TEXT DEFAULT '#0066cc',
  secondary_color TEXT DEFAULT '#f8f9fa',
  font_family TEXT DEFAULT 'Arial, sans-serif',
  header_text TEXT DEFAULT 'Diagnostic Report',
  footer_text TEXT DEFAULT 'This report was generated by DentaRad AI diagnostic services.',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.pdf_templates ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Admins can manage all templates" 
ON public.pdf_templates 
FOR ALL 
USING (get_current_user_role() = 'admin'::text);

-- Insert default template
INSERT INTO public.pdf_templates (name, company_name, company_address, header_text, footer_text) 
VALUES (
  'Default DentaRad Template',
  'DentaRad AI Diagnostics',
  '123 Medical Street, Healthcare City, HC 12345',
  'CBCT Diagnostic Report',
  'This report was generated by DentaRad AI diagnostic services. For questions, contact support@dentarad.com'
);

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_pdf_templates_updated_at
BEFORE UPDATE ON public.pdf_templates
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();